import './globals.css'
import '@ionic/react/css/core.css';

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { setupIonicReact } from '@ionic/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard BibiMob',
  description: 'Generated by Mello',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
