import './globals.css'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { middleware } from '../../middleware'

const inter = Inter({ subsets: ['latin'] })
// Add the favicon property to the Metadata type definition
interface CustomMetadata extends Omit<Metadata, 'icons'> {
  favicon: string
}

export const metadata: CustomMetadata = {
  title: 'Dashboard BibiMob',
  description: 'Generated by Mello',
  favicon: '/favicon.ico',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="pt-BR">
      <body className={inter.className}>
        {children}</body>
    </html>
  )
}

export const config = {
  middleware: [middleware],
}